### ISSUE TITLE
cant create a cluster role binding 

### ISSUE THREAD

**Issue by karmab** [openshift/openshift-restclient-python#146]
i m using the following resource definition file

```
kind: ClusterRoleBinding
metadata:
  labels:
    kubevirt.io: ''
  name: kubevirt-infra
roleRef:
#  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-infra
subjects:
- kind: ServiceAccount
  name: kubevirt-infra
  namespace: kube-system
```

when deploying it with a ansible task, i get an an error
- name: Creating ClusterRoleBinding kubevirt-infra
  k8s_v1beta1_cluster_role_binding:
    name: kubevirt-infra
    state: present
    src: /tmp/ClusterRoleBinding_kubevirt-infra.yml

Error parsing resource definition. Encountered roleRef_kind, which does not map to a module parameter. If this looks like a problem with the module, please open an issue at github.com/openshift/openshift-restclient-python/issues

the error seems to happen for everything below roleRef

**Comment by jwmatthews** [comment]
@fabianvf @djzager please bump the priority of this.

This is related to KubeVirt effort

**Comment by djzager** [comment]
@karmab I was able to get this to work with 2 changes to the Ansible code I see [in your provision.yaml](https://github.com/ansibleplaybookbundle/kubevirt-apb/blob/master/roles/kubevirt-apb/tasks/provision.yml) and your [template](https://github.com/ansibleplaybookbundle/kubevirt-apb/blob/master/roles/kubevirt-apb/templates/ClusterRoleBinding_kubevirt-infra.yml.j2).

1. `roleRef` --> `role_ref`
1. Removing namespace from the cluster level resource.

**Comment by djzager** [comment]
I remember discussing this issue with you @karmab but I want to confirm with you before I close this issue. Is this resolved?

**Comment by josdotso** [comment]
I'm seeing an error in ansible's k8s_raw along these lines w/openshift 0.5.0 on python3.6

Doesn't work, even if i change `roleRef` to `role_ref` and drop the namespace line.
```
          apiVersion: rbac.authorization.k8s.io/v1beta1
          kind: ClusterRoleBinding
          metadata:
            name: tiller
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - kind: ServiceAccount
              name: tiller
              namespace: kube-system
```

Can you advise @djzager ?
