### ISSUE TITLE
cant define custom resource definitions

### ISSUE THREAD

**Issue by karmab** [openshift/openshift-restclient-python#147]
when trying to define the following 

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ''
  name: virtualmachines.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: VirtualMachine
    plural: virtualmachines
    shortNames:
    - vm
    - vms
    singular: virtualmachine
  scope: Namespaced
  version: v1alpha1
```

using this ansible module

```
- name: Creating CustomResourceDefinition migrations.kubevirt.io
  k8s_v1beta1_custom_resource_definition:
    name: migrations.kubevirt.io
    namespace: "{{ namespace}}"
    state: present
    src: /tmp/CustomResourceDefinition_migrations.kubevirt.io.yml
```

i get this error 

```
TASK [kubevirt-apb : Creating CustomResourceDefinition virtualmachines.kubevirt.io] ***
fatal: [localhost]: FAILED! => {"changed": false, "error": null, "msg": "Failed to retrieve requested object: Error: method read_namespaced_custom_resource_definition not found for model custom_resource_definition. "}
```

**Comment by jwmatthews** [comment]
@fabianvf @djzager please bump the priority of this.

This is related to KubeVirt effort

**Comment by djzager** [comment]
recommendation here is to remove the `namespace` from the custom_resource_definition:

```
- name: Creating CustomResourceDefinition migrations.kubevirt.io
  k8s_v1beta1_custom_resource_definition:
    name: migrations.kubevirt.io
    state: present
    src: /tmp/CustomResourceDefinition_migrations.kubevirt.io.yml
```
