### ISSUE TITLE
Failed to create object: the server could not find the requested resource with ansible module and openshift

### ISSUE THREAD

**Issue by twhiston** [openshift/openshift-restclient-python#157]
Essentially the same as #121 but for openshift. I cannot currently create templates

```
- name: Create Template Instance
  openshift_v1_template_instance:
    host: "{{ openshift_host }}"
    api_key: "{{ oc_token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    namespace: "{{ project_name }}"
    name: trivial-test
    spec_template_objects:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: gitlab-token
            data:
              password: xxxxx
```
returns an error
```
The full traceback is:
  File "/var/folders/fs/8mwd9rjn6rn3sh22s9tqf4qc0000gp/T/ansible_lDEcMp/ansible_modlib.zip/ansible/module_utils/k8s_common.py", line 251, in _create
    k8s_obj = self.helper.create_object(namespace, body=request_body)
  File "/Users/twhiston/Library/Python/2.7/lib/python/site-packages/openshift/helper/base.py", line 272, in create_object
    raise self.get_exception_class()(msg, status=exc.status)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "error": 404, 
    "invocation": {
        "module_args": {
            "annotations": null, 
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "cert_file": null, 
            "context": null, 
            "debug": false, 
            "force": false, 
            "host": "my.server.com", 
            "key_file": null, 
            "kubeconfig": null, 
            "labels": null, 
            "name": "trivial-test", 
            "namespace": "nine-tom-test-managed", 
            "password": null, 
            "resource_definition": null, 
            "spec_requester_extra": null, 
            "spec_requester_groups": null, 
            "spec_requester_uid": null, 
            "spec_requester_username": null, 
            "spec_secret_name": null, 
            "spec_template_api_version": null, 
            "spec_template_kind": null, 
            "spec_template_labels": null, 
            "spec_template_message": null, 
            "spec_template_metadata_annotations": null, 
            "spec_template_metadata_labels": null, 
            "spec_template_metadata_name": null, 
            "spec_template_metadata_namespace": null, 
            "spec_template_objects": [
                {
                    "apiVersion": "v1", 
                    "data": {
                        "password": "xxxxxxxx"
                    }, 
                    "kind": "Secret", 
                    "metadata": {
                        "name": "gitlab-token"
                    }
                }
            ], 
            "spec_template_parameters": null, 
            "src": null, 
            "ssl_ca_cert": null, 
            "state": "present", 
            "username": null, 
            "verify_ssl": false
        }
    }, 
    "msg": "Failed to create object: the server could not find the requested resource"
}

```

```
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://my.server.com:8443
openshift v3.6.173.0.96
kubernetes v1.6.1+5115d708d7
```

```
ansible 2.5.0b2 (stable-2.5 61c1241a77) last updated 2018/02/22 00:21:03 (GMT +200)
  config file = /Users/twhiston/.ansible.cfg
  configured module search path = [u'/Users/twhiston/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/devel/lib/ansible
  executable location = /usr/local/Cellar/ansible/devel/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```
