### ISSUE TITLE
Dynamic Client should handle Lists

### ISSUE THREAD

**Issue by djzager** [openshift/openshift-restclient-python#175]
Currently, the dynamic client can't handle creating lists like https://github.com/dymurray/jupyterhub-apb/blob/c89ce32667d6dbf1f764e441084effe39f16375f/files/jupyterhub-templates.json

**Comment by gtema** [comment]
It would be also helpful, when single template contain list with API objects: http://paste.openstack.org/show/725140/
It lets you avoid structure like:
```
- name: "Set general configs and secrets state={{ state }}"
  k8s:
    state: '{{ state }}'
    definition: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'common_config.yaml') | from_yaml }}"
    - "{{ lookup('template', 'zuul_config.yaml') | from_yaml }}"
    - "{{ lookup('template', 'nodepool_config.yaml') | from_yaml }}"
```
