### ISSUE TITLE
Unsupported Media Type when try to update a ServiceMonitor

### ISSUE THREAD

**Issue by robsonpeixoto** [openshift/openshift-restclient-python#205]
When I try to create a custom resource, in my case a `ServiceMonitor` from `monitoring.coreos.com/v1` I got the error: `Failed to patch object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json\",\"reason\":\"UnsupportedMediaType\",\"code\":415}\\n'`

A ansible code example, but you need to run twice:
```yaml
-  k8s:
    state: present
    context: "your k8s context name"
    namespace: "monitoring"
    resource_definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: prometheus-operator
        labels:
          app: prometheus-operator
      spec:
        endpoints:
        - port: http
        selector:
          matchLabels:
            app: prometheus-operator
        namespaceSelector:
          matchNames:
          - monitoring

```
The openshift version it `0.7.1`. Below has the output from `pipenv graph`:
```
openshift==0.7.1
  - dictdiffer [required: Any, installed: 0.7.1]
  - jinja2 [required: Any, installed: 2.10]
    - MarkupSafe [required: >=0.23, installed: 1.0]
  - kubernetes [required: ==7.0.0, installed: 7.0.0]
    - adal [required: >=1.0.2, installed: 1.1.0]
      - cryptography [required: >=1.1.0, installed: 2.3.1]
        - asn1crypto [required: >=0.21.0, installed: 0.24.0]
        - cffi [required: >=1.7,!=1.11.3, installed: 1.11.5]
          - pycparser [required: Any, installed: 2.18]
        - idna [required: >=2.1, installed: 2.7]
        - six [required: >=1.4.1, installed: 1.11.0]
      - PyJWT [required: >=1.0.0, installed: 1.6.4]
      - python-dateutil [required: >=2.1.0, installed: 2.7.3]
        - six [required: >=1.5, installed: 1.11.0]
      - requests [required: >=2.0.0, installed: 2.19.1]
        - certifi [required: >=2017.4.17, installed: 2018.8.24]
        - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
        - idna [required: >=2.5,<2.8, installed: 2.7]
        - urllib3 [required: >=1.21.1,<1.24, installed: 1.23]
    - certifi [required: >=14.05.14, installed: 2018.8.24]
    - google-auth [required: >=1.0.1, installed: 1.5.1]
      - cachetools [required: >=2.0.0, installed: 2.1.0]
      - pyasn1-modules [required: >=0.2.1, installed: 0.2.2]
        - pyasn1 [required: >=0.4.1,<0.5.0, installed: 0.4.4]
      - rsa [required: >=3.1.4, installed: 3.4.2]
        - pyasn1 [required: >=0.1.3, installed: 0.4.4]
      - six [required: >=1.9.0, installed: 1.11.0]
    - python-dateutil [required: >=2.5.3, installed: 2.7.3]
      - six [required: >=1.5, installed: 1.11.0]
    - pyyaml [required: >=3.12, installed: 3.13]
    - requests [required: Any, installed: 2.19.1]
      - certifi [required: >=2017.4.17, installed: 2018.8.24]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.8, installed: 2.7]
      - urllib3 [required: >=1.21.1,<1.24, installed: 1.23]
    - requests-oauthlib [required: Any, installed: 1.0.0]
      - oauthlib [required: >=0.6.2, installed: 2.1.0]
      - requests [required: >=2.0.0, installed: 2.19.1]
        - certifi [required: >=2017.4.17, installed: 2018.8.24]
        - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
        - idna [required: >=2.5,<2.8, installed: 2.7]
        - urllib3 [required: >=1.21.1,<1.24, installed: 1.23]
    - setuptools [required: >=21.0.0, installed: 40.2.0]
    - six [required: >=1.9.0, installed: 1.11.0]
    - urllib3 [required: >=1.19.1,!=1.21, installed: 1.23]
    - websocket-client [required: >=0.32.0,!=0.42.*,!=0.41.*,!=0.40.0, installed: 0.52.0]
      - six [required: Any, installed: 1.11.0]
  - python-string-utils [required: Any, installed: 0.6.0]
  - ruamel.yaml [required: >=0.15, installed: 0.15.64]
  - six [required: Any, installed: 1.11.0]
```
