### ISSUE TITLE
Unable to patch lists

### ISSUE THREAD

**Issue by magne** [openshift/openshift-restclient-python#209]
I'm using Ansible 2.6.2 with the  'strategic-merge', 'merge' patch (44821 and 45284) and openshift 0.7.1, but there are still problems with resources containing lists. The following definition:
```
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: kube-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
kind: RoleBindingList
```
fails with the following error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:
  ValueError: name is required to patch rbac.authorization.k8s.io/v1.RoleBinding
  failed: [kube-01] (item=/root/kube-prometheus/manifests/prometheus-roleBindingSpecificNamespaces) => {
    "changed": false,
    "item": "/root/kube-prometheus/manifests/prometheus-roleBindingSpecificNamespaces",
    "module_stderr": "Traceback (most recent call last):
      File \"/tmp/ansible_ISz896/ansible_module_k8s.py\", line 165, in <module>
        main()
      File \"/tmp/ansible_ISz896/ansible_module_k8s.py\", line 161, in main
        KubernetesRawModule().execute_module()
      File \"/tmp/ansible_ISz896/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 98, in execute_module
      File \"/tmp/ansible_ISz896/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 223, in perform_action
      File \"/tmp/ansible_ISz896/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 241, in patch_resource
      File \"/usr/local/lib/python2.7/dist-packages/openshift/dynamic/client.py\", line 31, in inner
        resp = func(self, resource, *args, **kwargs)
      File \"/usr/local/lib/python2.7/dist-packages/openshift/dynamic/client.py\", line 188, in patch
        raise ValueError(\"name is required to patch {}.{}\".format(resource.group_version, resource.kind))
    ValueError: name is required to patch rbac.authorization.k8s.io/v1.RoleBinding",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1}
```

This is understandable, as the list does not have a name, but is it possible to have special handling of resource lists? BTW, the definition was generated with jsonnet and later converted to yaml, but I get the same error if I try to process the json file. (The definition is part of the prometheus-operator, https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus).

**Comment by fabianvf** [comment]
Yeah, I think there's an open issue for supporting list kinds, I just haven't been able to dedicate the time to adding it in. Currently I think you'd have to loop over the elements in the list in your Ansible, like

```yaml

- k8s:
    definition: '{{ item }}'
  loop: "{{ lookup('file', 'rolebindings.yaml')['items'] }}'
```

Does this work for you?
