### ISSUE TITLE
Template created but not processed

### ISSUE THREAD

**Issue by Sispheor** [openshift/openshift-restclient-python#219]
Hi,
I'm playing with the ansible module k8s.
I try to process an Openshift template.

Here is my task:
```yml
- name: Deploy the build of the backend
  k8s:
    state: present
    namespace: "{{ project_name }}"
    definition: "{{ lookup('template', '../../../openshift/templates/01-build_images.yml') | from_yaml }}"
```

The template is well instantiated with jinja but only created on the target openshift (I can get it via oc get templates).

My question is, how I can instantiate it? I'm supposed to add a "shell" task that will call oc apply command?
I think I'm missing something, thanks by advance for any hint !
