### ISSUE TITLE
question: how to deal with configmap + json + jinja templating

### ISSUE THREAD

**Issue by Sispheor** [openshift/openshift-restclient-python#230]
Hello, just a question. I have a config map to send. This last use json.

Here is my task:
```yml
- name: Front config map
  k8s:
    host: "{{ oc_host }}"
    api_key: "{{ oc_token }}"
    verify_ssl: no
    state: present
    namespace: "{{ project_name }}"
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: "{{ frontend_configmap_name }}"
      data:
        configuration.json:  |-
          {
            "url_back_end": "{{ frontend_application_url }}",
            "registration_sla_link_url": "{{ registration_sla_link_url }}",
            "registration_security_url": "{{ registration_security_url  }}",
            "registration_partnership_contracts_url": "{{ registration_partnership_contract_url }}",
            "registration_legal_logs_CNIL_url": "{{ registration_legal_logs_cnil_url }}"
          }
```

And the output of the module
```
TASK [frontend : Front config map] ****************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "error": 400, "msg": "Failed to create object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"ConfigMap in version \\\"v1\\\" cannot be handled as a ConfigMap: [pos 54]: json: expect char '\\\"' but got char '{'\",\"reason\":\"BadRequest\",\"code\":400}\n", "reason": "Bad Request", "status": 400}
```

Maybe there is a good practice to handle this. If I remove jinja parts it works.
