### ISSUE TITLE
can not update k8s configmap

### ISSUE THREAD

**Issue by pain400** [openshift/openshift-restclient-python#256]
1. create or update configmap task file
```yaml
- name: create or update app configmap
  k8s:
    state: present
    src: /opt/k8s/app.yaml
  register: execute_result
```

2. app configmap yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "app-config"
  namespace: "default"
data:
  SERVICE_NAME: "app"
  server_port: "20080"
```
3. Run the ansible task and exec command `kubectl get cm app-config -o yaml`
```
apiVersion: v1
data:
  SERVICE_NAME: app
  server_port: "20080"
kind: ConfigMap
...
```
4. edit app configmap yaml and add `tmp: "blabla"`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "app-config"
  namespace: "default"
data:
  SERVICE_NAME: "app"
  server_port: "20080"
  tmp: "blabla"
```
5. Run the ansible task and exec command `kubectl get cm app-config -o yaml`
```
apiVersion: v1
data:
  SERVICE_NAME: app
  server_port: "20080"
  tmp: "blabla"
kind: ConfigMap
...
```
6. edit app configmap yaml and remove `tmp: "blabla"`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "app-config"
  namespace: "default"
data:
  SERVICE_NAME: "app"
  server_port: "20080"
```
7. Run the ansible task and exec command `kubectl get cm app-config -o yaml`, **_the configuration data `tmp: "blabla"` still exists!_**
```
apiVersion: v1
data:
  SERVICE_NAME: app
  server_port: "20080"
  tmp: "blabla"
kind: ConfigMap
...
```
