### ISSUE TITLE
This module requires the OpenShift Python client

### ISSUE THREAD

**Issue by Asgoret** [openshift/openshift-restclient-python#265]
Playbook:
```
- name: Test secret
  hosts: localhost
  tasks:
  
    - name: Set simple object state="{{ state }}"
      k8s:
        api_key: " {DATA} "
        host: "{URL}"
        state: present
        definition: secret.yaml.j2
```

Error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "This module requires the OpenShift Python client. Try `pip install openshift`"}
```

But:
```
╰─$ pip show openshift                                                                                                                                           2 ↵
Name: openshift
Version: 0.8.4
Summary: OpenShift python client
Home-page: https://github.com/openshift/openshift-restclient-python
Author: OpenShift
Author-email: UNKNOWN
License: Apache License Version 2.0
Location: /Library/Python/2.7/site-packages
Requires: dictdiffer, jinja2, kubernetes, python-string-utils, ruamel.yaml, six
Required-by:
```

**Comment by fabianvf** [comment]
This usually isn't an issue with the Python client or with the Ansible module, it's a core behavior of Ansible, and if you try to run any other modules that require Python dependencies against localhost, you should see the same behavior. When Ansible connects to a machine, even localhost, it will default to using the system installation of Python (ie, `/usr/bin/python`). If you've installed modules in a different environment than the system installation, they will not be present in the system Python path. To get the behavior you expect (run Ansible, detect modules installed in environment), you need to ensure that Ansible is detecting the proper Python interpreter when it connects. Oftentimes this is fixed by setting `ansible_python_interpreter: '{{ ansible_playbook_python }}'`, which should work so long as Ansible is installed in the same environment as your dependencies.

You can use the `python_requirements_facts` module to determine if Ansible sees the dependencies when connecting to the machine. If you post the output of the following playbook, I can help debug:

```yaml
---
- hosts: localhost
   tasks:
    - python_requirements_facts:
        dependencies:
          - openshift

- hosts: localhost
   vars:
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
   tasks:
    - python_requirements_facts:
        dependencies:
          - openshift
```

For more technical background on the reason for this behavior, I will again link to Will's breakdown: https://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html
