### ISSUE TITLE
Unable to explicitly set the secureBoot: True flag  while posting the VM resource.

### ISSUE THREAD

**Issue by kbidarkar** [openshift/openshift-restclient-python#378]
We make use of KubeVirt to create VM on openshift.

Specifically, while creating an EFI SecureBoot VM, unable to explicitly set the `secureBoot: True` flag  while posting the VM resource.

Posting the below resource succeeds in creating a VM,  

NOTE: While posting , it does include  ` {'bootloader': {'efi': {'secureBoot': True}}} `  as seen above.
```
INFO Posting {'apiVersion': 'kubevirt.io/v1alpha3', 'kind': 'VirtualMachine', 'metadata': {'creationTimestamp': None, 'labels': {'kubevirt.io/vm': 'efi-secureboot-vm'}, 'name': 'efi-secureboot-vm'}, 'spec': {'running': False, 'template': {'metadata': {'creationTimestamp': None, 'annotations': {'ansible': '{"ansible_user": "fedora", "ansible_ssh_pass": "fedora", "ansible_become": true, "ansible_become_method": "sudo"}'}, 'labels': {'kubevirt.io/vm': 'efi-secureboot-vm', 'kubevirt.io/domain': 'efi-secureboot-vm'}}, 'spec': {'domain': {'cpu': {'cores': 1}, 'devices': {'disks': [{'disk': {'bus': 'virtio'}, 'name': 'containerdisk'}, {'disk': {'bus': 'virtio'}, 'name': 'cloudinitdisk'}], 'interfaces': [{'masquerade': {}, 'name': 'default'}], 'rng': {}}, 'machine': {'type': ''}, 'resources': {'requests': {'memory': '1024Mi'}}, 'features': {'smm': {'enabled': True}}, 'firmware': {'bootloader': {'efi': {'secureBoot': True}}}}, 'networks': [{'name': 'default', 'pod': {}}], 'terminationGracePeriodSeconds': 0, 'volumes': [{'containerDisk': {'image': 'quay.io/openshift-cnv/qe-cnv-tests-fedora:32'}, 'name': 'containerdisk'}, {'name': 'cloudinitdisk', 'cloudInitNoCloud': {'userData': '#cloud-config\npassword: fedora\nchpasswd: { expire: False }\n'}}]}}}}
```

But when we try to fetch the VM resource via `oc get vm <vm-name> -o yaml` from the setup, we do not see the `secureBoot: True` flag set.

```
spec:
  running: false
  template:
    metadata:
      annotations:
      labels:
        kubevirt.io/domain: efi-secureboot-vm
        kubevirt.io/vm: efi-secureboot-vm
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel8.2.0
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/openshift-cnv/qe-cnv-tests-fedora:32
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
status: {}
```
----
Later,

When creating the same VM resource via the `oc` binary using a yaml file works perfectly fine.

We can then see the following, in the output of the VM via `oc get`

```
firmware:
  bootloader:
    efi:
      secureBoot: true
```

Summary:

Actual:  `Output from the VM resource`
```
firmware:
  bootloader:
    efi: {}
```
Expected:  `Output from the VM resource`

```
firmware:
  bootloader:
    efi:
      secureBoot: true
```

**Comment by kbidarkar** [comment]
@fabianvf , Tried to enable `urllib3` debug , but didn't manage to enable it.

But today tried to create a VM directly with CURL command and we were able to create VM as expected successfully.

```
POST_URL=$URL/apis/kubevirt.io/v1alpha3/namespaces/virt-general-efi-secureboot-test-vm-with-efi-secureboot/virtualmachines
oc login $URL -u kubeadmin -p $PASSWORD
TOKEN=$(oc whoami -t)
oc create ns virt-general-efi-secureboot-test-vm-with-efi-secureboot
```
```
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer <PUT TOKEN HERE>' -d '{"apiVersion": "kubevirt.io/v1alpha3", "kind": "VirtualMachine", "metadata": {"name": "centos8-efi-secure-boot"}, "spec": {"template": {"spec": {"domain": {"resources": {"requests": {"memory": "64M"}}, "devices": {"rng": {}, "disks": [{"disk": {"bus": "virtio"}, "name": "dv-disk"}]}, "features": {"smm": {"enabled": true}}, "firmware": {"bootloader": {"efi": {"secureBoot": true}}}}, "volumes": [{"name": "dv-disk", "dataVolume": {"name": "centos8-efi-dv"}}], "nodeSelector": {"kubernetes.io/hostname": "74sfj-worker-bhftx"}}, "metadata": {"labels": {"kubevirt.io/vm": "centos8-efi-secure-boot", "kubevirt.io/domain": "centos8-efi-secure-boot"}}}, "running": false}}' -k $POST_URL
```

and we did have,

```
        firmware:
            bootloader:
              efi:
                secureBoot: true
```

So feel, probably something with openshift module?
