### ISSUE TITLE
Module 'k8s_v1beta1_deployment' is not working

### ISSUE THREAD

**Issue by Dieler** [openshift/openshift-restclient-python#48]
The module `k8s_v1beta1_deployment` for creating deployments always returns with the following:
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "error": 400, 
    "failed": true, 
    "msg": "Failed to create object: Deployment in version \"v1beta1\" cannot be handled as a Deployment: no kind \"Deployment\" is registered for version \"v1beta1\""
}
```
Here's how the module configuration in the playbook looks like:
```
- k8s_v1beta1_deployment:
    state: "{{ state }}"
    resource_definition:
      kind: Deployment
      apiVersion: extensions/v1beta1
      metadata:
        name: "controlcenter"
        namespace: "controlcenter"
        labels:
          component: "controlcenter"
      spec:
        revisionHistoryLimit: 10
        replicas: 3
        strategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
    ...
```
Environment:
* Ansible from source
* Openshift from source with k8s modules generated via openshift-ansible-gen modules
