### ISSUE TITLE
K8s deployment module not working with attribute minReadySeconds 

### ISSUE THREAD

**Issue by Dieler** [openshift/openshift-restclient-python#51]
Trying to create a k8s deployment with the module `k8s_v1beta1_deployment` returns with an error when the template spec contains the attribute `minReadySeconds`.

The module gets invoked like so:
```yaml
- k8s_v1beta1_deployment:
    state: "present"
    resource_definition:
      apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        name: "es-master"
        namespace: "controlcenter"
        labels:
          component: "elasticsearch"
          role: "master"
      spec:
        revisionHistoryLimit: 10
        replicas: 3
        template:
          metadata:
            labels:
              component: "elasticsearch"
              role: "master"
              ...
          spec:
            ...
            minReadySeconds: 30
            containers:
            ...
```
Environment:
* Ansible from source
* Openshift from source with k8s modules generated via openshift-ansible-gen modules

Error message:
```json
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Error parsing resource definition. Encountered spec_template_spec_min_ready_seconds, which does not map to a module parameter. If this looks like a problem with the module, please open an issue at github.com/openshift/openshift-restclient-python/issues"
}
```
