### ISSUE TITLE
Conversion from string to int Fails When Creating a Service with Variables

### ISSUE THREAD

**Issue by marc-sensenich** [openshift/openshift-restclient-python#53]
I'm using the ansible.kubernetes-modules, which utilizes this library, to create objects inside of kubernetes and  found a case where the module can not convert a string to an integer from variables.

**Expected results**
Ok deployment

**Actual results**
"msg": "Failed to create object: Service \"test-service\" is invalid: spec.ports[0].targetPort: Invalid value: \"443\": must contain at least one letter or number (a-z, 0-9)"

**vars.yml**
```yaml
---
k8s_namespace: hello
k8s_service_name: test-service
ports:
  - name: http
    port: 80
    target_port: 80
  - name: https
    port: 443
    target_port: 443
```
**example task**
```yaml
- name: Create a publically exposed service
  k8s_v1_service:
    name: "{{ k8s_service_name}}"
    namespace: "{{ k8s_namespace }}"
    state: present
    ports:
      - port: "{{ item.port }}"
        target_port: "{{ item.target_port }}"
        name: "{{ item.name }}"
    debug: "{{ debug_enabled }}"
    type: LoadBalancer
  with_items:
    - "{{ ports }}"
```

**Comment by fabianvf** [comment]
This is an issue with the way the kubernetes API spec defines the targetPort. Even though technically it should accept either an int or a  string, the spec just flags it as a string type and therefore it is validated as a string. I think if you put the port numbers inside quotes this issue would go away.

```yaml
ports:
  - name: http
    port: 80
    target_port: "80"
  - name: https
    port: 443
    target_port: "443"
```
