### ISSUE TITLE
Malformed object with multiple triggers

### ISSUE THREAD

**Issue by awiddersheim** [openshift/openshift-restclient-python#69]
When using the Ansibles module I have something like this configured.

```
- name: create deployment config
  openshift_v1_deployment_config:
    state: present
    resource_definition:
      metadata:
        name: example
        namespace: example
        labels:
          app: example
      spec:
        strategy:
          type: Rolling
          rollingParams:
            updatePeriodSeconds: 1
            intervalSeconds: 1
            timeoutSeconds: 600
            maxUnavailable: 25%
            maxSurge: 25%
        triggers:
          - type: ConfigChange
          - type: ImageChange
            imageChangeParams:
              automatic: true
              containerNames:
                - memcached
              _from:
                kind: ImageStreamTag
                name: memcached:1.4-alpine
          - type: ImageChange
            imageChangeParams:
              automatic: true
              containerNames:
                - nginx
              _from:
                kind: ImageStreamTag
                name: nginx:openshift
        replicas: 1
        selector:
          app: example
        template:
          metadata:
            name: example
            labels:
              app: example
          spec:
            containers:
              - name: memcached
                image: memcached:1.4-alpine
                args: ["-p", "11211", "-m", "200"]
                ports:
                  - name: memcached
                    containerPort: 11211
                    protocol: TCP
                terminationMessagePath: /dev/termination-log
                imagePullPolicy: Always
              - name: nginx
                image: nginx:1.13-alpine
                command: ["nginx"]
                args: ["-c", "/config/nginx.conf", "-g", "daemon off;"]
                ports:
                  - name: nginx
                    containerPort: 8443
                    protocol: TCP
                terminationMessagePath: /dev/termination-log
                imagePullPolicy: Always
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
```

The object that gets created to send to the API looks like the following:

```
        "triggers": [
            {
                "type": "ConfigChange",
                "image_change_params": null
            },
            {
                "type": "ImageChange",
                "image_change_params": {
                    "last_triggered_image": null,
                    "_from": {
                        "kind": "ImageStreamTag",
                        "name": "nginx:openshift",
                        "resource_version": null,
                        "field_path": null,
                        "api_version": null,
                        "uid": null
                    },
                    "automatic": true,
                    "container_names": [
                        "memcached",
                        "nginx"
                    ]
                }
            },
            {
                "type": "ImageChange",
                "image_change_params": {
                    "last_triggered_image": null,
                    "_from": {
                        "kind": "ImageStreamTag",
                        "name": "nginx:openshift",
                        "resource_version": null,
                        "field_path": null,
                        "api_version": null,
                        "uid": null
                    },
                    "automatic": true,
                    "container_names": [
                        "nginx",
                        "memcached"
                    ]
                }
            }
        ]
```

It should look like this:

```
       "triggers": [
            {
                "type": "ConfigChange",
                "image_change_params": null
            },
            {
                "type": "ImageChange",
                "image_change_params": {
                    "last_triggered_image": null,
                    "_from": {
                        "kind": "ImageStreamTag",
                        "name": "memcached:1.4-alpine",
                        "resource_version": null,
                        "field_path": null,
                        "api_version": null,
                        "uid": null
                    },
                    "automatic": true,
                    "container_names": [
                        "memcached"
                    ]
                }
            },
            {
                "type": "ImageChange",
                "image_change_params": {
                    "last_triggered_image": null,
                    "_from": {
                        "kind": "ImageStreamTag",
                        "name": "nginx:openshift",
                        "resource_version": null,
                        "field_path": null,
                        "api_version": null,
                        "uid": null
                    },
                    "automatic": true,
                    "container_names": [
                        "nginx"
                    ]
                }
            }
        ]
```
