### ISSUE TITLE
Failures when using openshift_v1_role_binding module

### ISSUE THREAD

**Issue by jcpowermac** [openshift/openshift-restclient-python#73]
Tasks
```
- name: Create RoleBinding from Ansible Template
  template:
    src: rolebinding.yaml.j2
    dest: /tmp/rolebinding.yaml
  register: rolebinding

- name: Create RoleBinding
  openshift_v1_role_binding:
    name: "{{ jenkins_service_name }}_edit"
    namespace: "{{ namespace }}"
    src: "{{ rolebinding.dest | default(rolebinding.path) }}"
  ignore_errors: True

- name: Create RoleBinding
  openshift_v1_role_binding:
    name: "{{ jenkins_service_name }}_edit"
    namespace: "{{ namespace }}"
    role_ref_name: edit
    subjects:
      - kind: "ServiceAccount"
        name: "{{ jenkins_service_name }}"
  ignore_errors: True

- name: Create RoleBinding
  command: "oc create -f {{ rolebinding.dest | default(rolebinding.path) }} -n {{ namespace }}"
  ignore_errors: True
```
Jinja Template - rolebinding.yaml.j2
```
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: "{{ jenkins_service_name }}_edit"
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ jenkins_service_name }}
```
/tmp/rolebinding.yaml
```
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: "jenkins_edit"
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: jenkins
```

Task failure using template
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotations": null, 
            "api_key": null, 
            "cert_file": null, 
            "context": null, 
            "debug": false, 
            "force": false, 
            "group_names": null, 
            "host": null, 
            "key_file": null, 
            "kubeconfig": null, 
            "labels": null, 
            "name": "jenkins_edit", 
            "namespace": "jenkins", 
            "password": null, 
            "resource_definition": null, 
            "role_ref_api_version": null, 
            "role_ref_field_path": null, 
            "role_ref_kind": null, 
            "role_ref_name": "jenkins_edit", 
            "role_ref_namespace": "jenkins", 
            "role_ref_resource_version": null, 
            "role_ref_uid": null, 
            "src": "/tmp/rolebinding.yaml", 
            "ssl_ca_cert": null, 
            "state": "present", 
            "subjects": null, 
            "user_names": null, 
            "username": null, 
            "verify_ssl": null
        }
    }, 
    "msg": "Error parsing resource definition. Encountered roleRef_name, which does not map to a module parameter. If this looks like a problem with the module, please open an issue at github.com/openshift/openshift-restclient-python/issues"
}
```
Task failure using module options only
**NOTE**: The `role_ref_name` argument is wrong it should be edit.
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "error": 404, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotations": null, 
            "api_key": null, 
            "cert_file": null, 
            "context": null, 
            "debug": false, 
            "force": false, 
            "group_names": null, 
            "host": null, 
            "key_file": null, 
            "kubeconfig": null, 
            "labels": null, 
            "name": "jenkins_edit", 
            "namespace": "jenkins", 
            "password": null, 
            "resource_definition": null, 
            "role_ref_api_version": null, 
            "role_ref_field_path": null, 
            "role_ref_kind": null, 
            "role_ref_name": "jenkins_edit", 
            "role_ref_namespace": "jenkins", 
            "role_ref_resource_version": null, 
            "role_ref_uid": null, 
            "src": null, 
            "ssl_ca_cert": null, 
            "state": "present", 
            "subjects": [
                {
                    "kind": "ServiceAccount", 
                    "name": "jenkins"
                }
            ], 
            "user_names": null, 
            "username": null, 
            "verify_ssl": null
        }
    }, 
    "msg": "Failed to create object: role \"jenkins_edit\" not found"
}
```
Succeed using `oc create`
```
changed: [localhost] => {
    "changed": true, 
    "cmd": [
        "oc", 
        "create", 
        "-f", 
        "/tmp/rolebinding.yaml", 
        "-n", 
        "jenkins"
    ], 
    "delta": "0:00:00.207404", 
    "end": "2017-07-20 10:01:49.794717", 
    "invocation": {
        "module_args": {
            "_raw_params": "oc create -f /tmp/rolebinding.yaml -n jenkins", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2017-07-20 10:01:49.587313", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "rolebinding \"jenkins_edit\" created", 
    "stdout_lines": [
        "rolebinding \"jenkins_edit\" created"
    ]
}
```
